version: 2

snapshot:
  widths: [1280, 1440]  # Desktop-only: desktop and large desktop
  
  percy-css: |
    /* Hide dynamic elements */
    .loading-spinner { display: none !important; }
    .timestamp { display: none !important; }
    
    /* Disable animations */
    *, *::before, *::after {
      animation-duration: 0s !important;
      transition-duration: 0s !important;
    }
